---
apiVersion: v1
kind: Service
metadata:
  name: data-api
  labels:
    name: data-api
  namespace: {{ .Values.namespace }}
spec:
  type: "ClusterIP"
  ports:
  - name: http
    port: 80
    targetPort: 3009
  selector:
    app: data-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "data-api"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ default 1 .Values.dataApi.replicas }}
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - image: {{ .Values.dataApi.registryServer }}/{{ .Values.dataApi.imageName }}:{{ .Values.dataApi.imageTag }} 
          imagePullPolicy: Always
          name: data-api
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: pwd
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights-secret
                  key: appinsights                   
          ports:
          - containerPort: 3009
            protocol: TCP
      restartPolicy: Always
