---
apiVersion: v1
kind: Service
metadata:
  name: flights-api
  labels:
    name: flights-api
  namespace: {{ .Values.namespace }}
spec:
  type: "ClusterIP"
  ports:
  - name: http
    port: 80
    targetPort: 3003
  selector:
    app: flights-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "flights-api"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ default 1 .Values.flightsApi.replicas }}
  selector:
    matchLabels:
      app: flights-api
  template:
    metadata:
      labels:
        app: flights-api
    spec:
      containers:
        - image: {{ .Values.flightsApi.registryServer }}/{{ .Values.flightsApi.imageName }}:{{ .Values.flightsApi.imageTag }} 
          imagePullPolicy: Always
          name: flights-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.{{ .Values.namespace }}.svc.cluster.local/     
          ports:
          - containerPort: 3003
            protocol: TCP
      restartPolicy: Always
