---
apiVersion: v1
kind: Service
metadata:
  name: quakes-api
  labels:
    name: quakes-api
  namespace: {{ .Values.namespace }}
spec:
  type: "ClusterIP"
  ports:
  - name: http
    port: 80
    targetPort: 3012
  selector:
    app: quakes-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "quakes-api"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ default 1 .Values.quakesApi.replicas }}
  selector:
    matchLabels:
      app: quakes-api
  template:
    metadata:
      labels:
        app: quakes-api
    spec:
      containers:
        - image: {{ .Values.quakesApi.registryServer }}/{{ .Values.quakesApi.imageName }}:{{ .Values.quakesApi.imageTag }}
          imagePullPolicy: Always
          name: quakes-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.{{ .Values.namespace }}.svc.cluster.local/     
          ports:
          - containerPort: 3012
            protocol: TCP
      restartPolicy: Always
