---
apiVersion: v1
kind: Service
metadata:
  name: weather-api
  labels:
    name: weather-api
  namespace: {{ .Values.namespace }}
spec:
  type: "ClusterIP"
  ports:
  - name: http
    port: 80
    targetPort: 3015
  selector:
    app: weather-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "weather-api"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ default 1 .Values.weatherApi.replicas }}
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - image: {{ .Values.weatherApi.registryServer }}/{{ .Values.weatherApi.imageName }}:{{ .Values.weatherApi.imageTag }}
          imagePullPolicy: Always
          name: weather-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.{{ .Values.namespace }}.svc.cluster.local/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.{{ .Values.namespace }}.svc.cluster.local/       
          ports:
          - containerPort: 3015
            protocol: TCP
      restartPolicy: Always
