---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: {{ .Values.namespace }}
spec:
  type: "ClusterIP"
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx 
          imagePullPolicy: Always
          name: nginx
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"     
          ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
