apiVersion: v1
kind: Pod
metadata:
 name: static-azure-file-volume
 namespace: snippets
spec:
 containers:
  - image: nginx
    name: static-azure-file-volume
    volumeMounts:
    - mountPath: /mnt/azure
      name: volume1
 volumes:
  - name: volume1
    azureFile:
      secretName: handelsblatt-storage-secret
      shareName: static-azure-file-volume
      readOnly: false