apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: captureorder
spec:
  selector:
      matchLabels:
        app: frontend
  replicas: 1
  template:
      metadata:
        labels:
            app: frontend
      spec:
        serviceAccountName: frontend
        containers:
        - name: frontend-sidecar
          image: fnbk/captureorder-frontend-sidecar:v0.0.8
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 5000
              path: /
              scheme: HTTP
          livenessProbe:
            httpGet:
              port: 5000
              path: /
              scheme: HTTP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: LOOKUP_NAMESPACE
            value: "captureorder"
          - name: LOOKUP_SERVICE
            value: "backend"  
          ports:
          - containerPort: 5000
        - name: frontend
          image: fnbk/captureorder-frontend:v0.0.5
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: SIDECAR_PORT
            value: "5000"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: captureorder
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer