apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: hello
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: tutum/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: hello
spec:
  selector:
    app: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
