---
apiVersion: apps/v1
kind: Pod
metadata:
  name: hello
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nginx:1.15.0-alpine
        ports:
        - containerPort: 80
      - name: mein-init-contianer
        kind: initContainer
        image: nginx:1.15.0-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello
spec:
  selector:
    app: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
