apiVersion: v1
kind: Pod
metadata:
 name: static-managed-azure-disk-volume
 namespace: snippets
spec:
 containers:
  - image: nginx
    name: static-azure-disk-volume
    volumeMounts:
    - mountPath: /mnt/azure
      name: volume1
 volumes:
  - name: volume1
    azureDisk:
      diskName: static-managed-azure-disk-volume
      kind: Managed
      diskURI: /subscriptions/4427b046-b93b-421e-b487-f1bf5214fcb1/resourceGroups/MC_eagle-cluster_eagle_westeurope/providers/Microsoft.Compute/disks/static-managed-azure-disk-volume