---
#
#
#
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: managed-azure-disk-volume
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS # Standard_LRS (HDD), Premium_LRS (SSD)
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: managed-azure-disk-volume
  namespace: snippets
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-azure-disk-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: managed-azure-disk-volume
  namespace: snippets
spec:
  containers:
  - image: nginx
    name: managed-azure-disk-volume
    command:
    - /bin/sh
    - -c
    - while true; do echo $(date) >> /mnt/azure/outfile; sleep 1; done
    volumeMounts:
    - name: volume1
      mountPath: /mnt/azure
  volumes:
  - name: volume1
    persistentVolumeClaim:
      claimName: managed-azure-disk-volume
---

