#
# happy
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy
  namespace: happyday
spec:
  selector:
    matchLabels:
      app: happy
  replicas: 1
  template:
    metadata:
      labels:
        app: happy
    spec:
      containers:
      - name: happy
        image: nginx:1.15.0-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: happy
  namespace: happyday
spec:
  selector:
    app: happy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
#
# day
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: day
  namespace: happyday
spec:
  selector:
    matchLabels:
      app: day
  replicas: 1
  template:
    metadata:
      labels:
        app: day
    spec:
      containers:
      - name: day
        image: tutum/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: day
  namespace: happyday
spec:
  selector:
    app: day
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
#
# ingress
#
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: happyday-ingress
  namespace: happyday
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - eagle.westeurope.cloudapp.azure.com
    secretName: aks-ingress-tls
  rules:
  - host: eagle.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: happy
          servicePort: 80
      - path: /day
        backend:
          serviceName: day
          servicePort: 80
---